export const AUTH_ACCESS_PRIVATE_KEY = 'AUTH_ACCESS_PRIVATE_KEY';
export const AUTH_ACCESS_PUBLIC_KEY = 'AUTH_ACCESS_PUBLIC_KEY';
export const AUTH_REFRESH_PRIVATE_KEY = 'AUTH_REFRESH_PRIVATE_KEY';
export const AUTH_REFRESH_PUBLIC_KEY = 'AUTH_REFRESH_PUBLIC_KEY';
export const AUTH_TOKEN_PEPPER = 'AUTH_TOKEN_PEPPER';
